# ============================================================
# SMD-CHD - SMD Computer Health Device - Version 1.4.0
# Local-first, read-only Windows diagnostic application
# ============================================================
$ErrorActionPreference='Continue'; $ScriptRoot=Split-Path -Parent $MyInvocation.MyCommand.Path; $Root=Split-Path $ScriptRoot -Parent; $ModulesPath=Join-Path $ScriptRoot 'modules'; $ReportsPath=Join-Path $Root 'reports'; $LogsPath=Join-Path $Root 'logs'; @($ReportsPath,$LogsPath) | ForEach-Object { if(-not(Test-Path $_)){New-Item -ItemType Directory -Path $_ -Force|Out-Null} }
$moduleFiles=@('CPU.ps1','RAM.ps1','Storage.ps1','Network.ps1','Windows.ps1','Security.ps1','Inventory.ps1','GPU.ps1','Battery.ps1','Thermal.ps1','Recommendations.ps1','History.ps1','HealthScore.ps1'); foreach($file in $moduleFiles){$path=Join-Path $ModulesPath $file;if(Test-Path $path){. $path}else{Write-Host "[INFO] Optional module unavailable: $file" -ForegroundColor Cyan}}
$Global:SMDResults=[ordered]@{CPU=$null;RAM=$null;Storage=$null;Network=$null;Windows=$null;Security=$null;Inventory=$null;GPU=$null;Battery=$null;Thermal=$null;HealthScore=$null;Trend=$null;Technician=[ordered]@{Customer='';Device='';Technician='';JobReference='';Notes=''};ReportId=$null;Timestamp=Get-Date}
function Show-Banner { Clear-Host; Write-Host '========================================' -ForegroundColor Cyan; Write-Host '             SMD-CHD' -ForegroundColor White; Write-Host '     SMD COMPUTER HEALTH DEVICE' -ForegroundColor Cyan; Write-Host '========================================' -ForegroundColor Cyan; Write-Host '  Version 1.4.0 | Safe • Local • Read-only' -ForegroundColor DarkGray; Write-Host '' }
function Pause-SMD { Write-Host ''; Write-Host 'Press any key to continue...' -ForegroundColor DarkGray; try{$null=$Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')}catch{Read-Host|Out-Null} }
function Write-Status { param([string]$Status,[string]$Message); $color=switch($Status.ToUpper()){PASS{'Green'}WARNING{'Yellow'}CRITICAL{'Red'}INFO{'Cyan'}default{'White'}}; Write-Host ('[{0,-8}] {1}' -f $Status,$Message) -ForegroundColor $color }
function Show-Menu { Write-Host '----------------------------------------' -ForegroundColor DarkCyan; @('[1] Full Computer Health Check','[2] CPU Check','[3] RAM Check','[4] Storage Check','[5] Network Check','[6] Windows Check','[7] Security Check','[8] Computer Inventory','[9] GPU Check','[10] Battery Health','[11] Thermal Check','[12] Health Recommendations','[13] Diagnostic History','[14] Technician / Service Report','[15] Generate Professional HTML Report','[0] Exit')|ForEach-Object{Write-Host "  $_"}; Write-Host '----------------------------------------' -ForegroundColor DarkCyan }
function Invoke-SafeDiagnostic { param([string]$Name,[scriptblock]$Action); try { & $Action } catch { [PSCustomObject]@{Status='INFO';Summary="$Name diagnostics unavailable";Details=@("The application continued safely: $($_.Exception.Message)")} } }
function Run-FullCheck { Write-Host "`n>>> Running Full Computer Health Check...`n" -ForegroundColor Cyan; $map=@{CPU='Get-CPUHealth';RAM='Get-RAMHealth';Storage='Get-StorageHealth';Network='Get-NetworkHealth';Windows='Get-WindowsHealth';Security='Get-SecurityHealth';Inventory='Get-ComputerInventory';GPU='Get-GPUHealth';Battery='Get-BatteryHealth';Thermal='Get-ThermalHealth'}; foreach($key in $map.Keys){$Global:SMDResults[$key]=Invoke-SafeDiagnostic $key ([scriptblock]::Create($map[$key]))}; $Global:SMDResults.HealthScore=Get-HealthScore $Global:SMDResults; $Global:SMDResults.Timestamp=Get-Date; $Global:SMDResults.Trend=Get-HealthTrend $LogsPath $Global:SMDResults.HealthScore.Score; Save-DiagnosticHistory $Global:SMDResults $Global:SMDResults.HealthScore $LogsPath|Out-Null; Write-Host '========== HEALTH SUMMARY ==========' -ForegroundColor Cyan; Write-Host "Overall Health Score : $($Global:SMDResults.HealthScore.Score) / 100"; Write-Host "Status               : $($Global:SMDResults.HealthScore.Status)"; foreach($key in $map.Keys){if($Global:SMDResults[$key]){Write-Status $Global:SMDResults[$key].Status "$key - $($Global:SMDResults[$key].Summary)"}}; Write-Host $Global:SMDResults.Trend.Summary; Pause-SMD }
function Show-Result { param($Name,$Result); Write-Host "`n=== $Name ===" -ForegroundColor Cyan; if($Result){Write-Status $Result.Status $Result.Summary; @($Result.Details)|ForEach-Object{Write-Host "  $_"}}else{Write-Status INFO 'No result available'}; Pause-SMD }
function Read-TechnicianInfo { $Global:SMDResults.Technician.Customer=Read-Host 'Customer name (optional)'; $Global:SMDResults.Technician.Device=Read-Host 'Customer/device reference (optional)'; $Global:SMDResults.Technician.Technician=Read-Host 'Technician name (optional)'; $Global:SMDResults.Technician.JobReference=Read-Host 'Job/reference number (optional)'; $Global:SMDResults.Technician.Notes=Read-Host 'Technician notes (optional)' }
function New-ReportId { return ('SMD-CHD-{0}-{1}' -f (Get-Date -Format 'yyyyMMdd-HHmmss'),(Get-Random -Minimum 1000 -Maximum 9999).ToString('X4')) }
function Html([object]$Value){if($null -eq $Value){return ''};return [System.Net.WebUtility]::HtmlEncode([string]$Value)}
function Generate-HTMLReport { if(-not $Global:SMDResults.HealthScore){Write-Host 'Run option 1 first.' -ForegroundColor Yellow;Pause-SMD;return}; if(-not $Global:SMDResults.ReportId){$Global:SMDResults.ReportId=New-ReportId}; $t=$Global:SMDResults.Technician;$h=$Global:SMDResults.HealthScore;$inv=$Global:SMDResults.Inventory;$rows=''; foreach($name in @('CPU','RAM','Storage','GPU','Network','Windows','Security','Battery','Thermal')){$r=$Global:SMDResults[$name];$rows+="<tr><td>$(Html $name)</td><td class='$(Html $r.Status.ToLower())'>$(Html $r.Status)</td><td>$(Html $r.Summary)</td></tr>"}; $problems=if($h.Warnings.Count -or $h.CriticalIssues.Count){(@($h.CriticalIssues)+@($h.Warnings)|ForEach-Object{"<li>$(Html $_)</li>"}) -join ''}else{'<li>No problems detected by the completed checks.</li>'}; $recs=if($h.Recommendations.Count){($h.Recommendations|ForEach-Object{"<li>$(Html $_.Text)</li>"}) -join ''}else{'<li>No recommendations were generated from the completed results.</li>'}; $checklist=@('Check Windows updates','Check storage space','Check startup applications','Check security','Check network','Check GPU driver','Check battery','Check system health','Check cooling/ventilation')|ForEach-Object{"<li>☐ $(Html $_)</li>"}; $file=Join-Path $ReportsPath ('SMD-Service-Report_{0}.html' -f (Get-Date -Format 'yyyyMMdd_HHmmss')); $html=@"
<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>SMD SERVICE REPORT - $($Global:SMDResults.ReportId)</title><style>body{font-family:Segoe UI,Arial;background:#eef2f7;color:#172033;margin:0;padding:18px}.sheet{max-width:1000px;margin:auto;background:white;padding:28px;box-shadow:0 2px 14px #bcc6d3}h1{color:#075985;margin-bottom:2px}.muted{color:#526174}.score{text-align:center;background:#075985;color:#fff;padding:20px;border-radius:8px}.score strong{font-size:48px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #dbe3ec}.pass{color:#16803c}.warning{color:#a16207}.critical{color:#b91c1c}.info{color:#0369a1}.box{background:#f7f9fc;padding:15px;margin:18px 0;border-left:4px solid #38bdf8}footer{margin-top:28px;color:#526174;text-align:center}@media print{body{background:#fff;padding:0}.sheet{box-shadow:none}}@media(max-width:600px){.sheet{padding:15px}th,td{font-size:13px}}</style></head><body><main class='sheet'><h1>SMD SERVICE REPORT</h1><div class='muted'>SMD-CHD — SMD Computer Health Device | Version 1.4.0</div><p><b>Customer:</b> $(Html $t.Customer) &nbsp; <b>Device:</b> $(Html $t.Device) &nbsp; <b>Technician:</b> $(Html $t.Technician) &nbsp; <b>Job Reference:</b> $(Html $t.JobReference)</p><p><b>Diagnostic Date:</b> $(Html $Global:SMDResults.Timestamp) &nbsp; <b>Report ID:</b> $(Html $Global:SMDResults.ReportId) &nbsp; <b>Computer:</b> $(Html $inv.ComputerName)</p><section class='score'><div>Overall Health Score</div><strong>$($h.Score)/100</strong><div>$($h.Status)</div></section><h2>Diagnostic Results</h2><table><tr><th>Component</th><th>Status</th><th>Summary</th></tr>$rows</table><div class='box'><h2>Problems Detected</h2><ul>$problems</ul></div><div class='box'><h2>Recommendations</h2><ul>$recs</ul></div><h2>Maintenance Checklist</h2><ul>$($checklist -join '')</ul><h2>Health Trend</h2><p>$(Html $Global:SMDResults.Trend.Summary)</p><h2>Technician Notes</h2><p>$(Html $t.Notes)</p><footer>SMD-CHD — Safe • Local • Reliable<br>Version 1.4.0</footer></main></body></html>
"@; $html|Out-File $file -Encoding UTF8;Write-Host "Report generated: $file" -ForegroundColor Green;try{Start-Process $file}catch{};Pause-SMD }
function Show-History { $trend=if($Global:SMDResults.HealthScore){Get-HealthTrend $LogsPath $Global:SMDResults.HealthScore.Score}else{Get-HealthTrend $LogsPath 0}; Write-Host "`n$($trend.Summary)" -ForegroundColor Cyan; $files=@(Get-ChildItem (Get-DiagnosticHistoryPath $LogsPath) -Filter 'diagnostic_*.json' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 10);foreach($f in $files){$x=Get-Content -Raw $f|ConvertFrom-Json;Write-Host "$($x.DateTime) | $($x.ComputerName) | $($x.Score)/100 | $($x.Status)"};Pause-SMD }
while($true){Show-Banner;Show-Menu;$choice=Read-Host 'Select an option';switch($choice){'1'{Run-FullCheck};'2'{$Global:SMDResults.CPU=Get-CPUHealth;Show-Result CPU $Global:SMDResults.CPU};'3'{$Global:SMDResults.RAM=Get-RAMHealth;Show-Result RAM $Global:SMDResults.RAM};'4'{$Global:SMDResults.Storage=Get-StorageHealth;Show-Result Storage $Global:SMDResults.Storage};'5'{$Global:SMDResults.Network=Get-NetworkHealth;Show-Result Network $Global:SMDResults.Network};'6'{$Global:SMDResults.Windows=Get-WindowsHealth;Show-Result Windows $Global:SMDResults.Windows};'7'{$Global:SMDResults.Security=Get-SecurityHealth;Show-Result Security $Global:SMDResults.Security};'8'{$Global:SMDResults.Inventory=Get-ComputerInventory;Show-Result Inventory ([PSCustomObject]@{Status='INFO';Summary='Computer inventory';Details=($Global:SMDResults.Inventory.GetEnumerator()|ForEach-Object{"$($_.Name): $($_.Value)")})};'9'{$Global:SMDResults.GPU=Get-GPUHealth;Show-Result GPU $Global:SMDResults.GPU};'10'{$Global:SMDResults.Battery=Get-BatteryHealth;Show-Result Battery $Global:SMDResults.Battery};'11'{$Global:SMDResults.Thermal=Get-ThermalHealth;Show-Result Thermal $Global:SMDResults.Thermal};'12'{if(-not $Global:SMDResults.HealthScore){Write-Host 'Run option 1 first.' -ForegroundColor Yellow}else{$Global:SMDResults.HealthScore.Recommendations|ForEach-Object{Write-Host "[$($_.Category)] $($_.Text)"}};Pause-SMD};'13'{Show-History};'14'{Read-TechnicianInfo;if(-not $Global:SMDResults.HealthScore){Run-FullCheck}};'15'{Generate-HTMLReport};'0'{Write-Host 'Thank you for using SMD-CHD.' -ForegroundColor Cyan;break};default{Write-Host 'Invalid option.' -ForegroundColor Yellow;Start-Sleep 1}}}
